version: '3'
services:
  web:
    image: huguesmcd/super-heroes:frontend-latest
    ports:
      - "4001:8081"

  backend:
    image: huguesmcd/super-heroes:backend-latest

    expose:
      - "8080"
